### ISSUE TITLE
[BUG] 当不传入参数时无法使用指令

### ISSUE THREAD

**Issue by keifergu** [mimoning/v-draggable#28]
![image](https://user-images.githubusercontent.com/12066055/30584947-efb2983a-9cf0-11e7-8eab-4e90521bd3c8.png)
![image](https://user-images.githubusercontent.com/12066055/30584987-09568134-9cf1-11e7-8c50-b6126b0b379b.png)

**Comment by mimoning** [comment]
look at #29 #30 two hotfixes
